### ISSUE TITLE
Not showing close, avatar image on  Firefox or Chrome 72+

### ISSUE THREAD

**Issue by ganzorig** [erxes/erxes-widgets#110]

**Comment by karser** [comment]
I also noticed this bug. It attempts to load avatars from 
```
https://widgets.erxes.mydomain.com/images/avatar-colored.svg
```
![image](https://user-images.githubusercontent.com/1675033/54399463-3b5e9000-46c7-11e9-9ddb-51aee4a49985.png)

Although the correct url is:
https://erxes.mydomain.com/images/avatar-colored.svg
![image](https://user-images.githubusercontent.com/1675033/54399533-942e2880-46c7-11e9-8ca0-0d6dff2c3155.png)

**Comment by karser** [comment]
I figured out that this issue only applies to `admin@erxes.io` user that is created by `erxes-api yarn initProject`. Looks like that's because of this relative link https://github.com/erxes/erxes-widgets/blob/develop/client/messenger/components/common/Supporters.tsx#L17
```
  getAvatar(avatar: string) {
    if (!avatar || avatar === "/images/avatar-colored.svg") {
      return defaultAvatar;
    }
```

Manually created users contain embedded avatars, e.g `data:image/svg+xml;utf8,<svg ...` (even for default avatars), so there is no issue here.
